// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadAdaptiveWorkflowState } from "./ThreadAdaptiveWorkflowState";
import type { ThreadWorkflowStateOperation } from "./ThreadWorkflowStateOperation";

export type ThreadWorkflowStateUpdateParams = { threadId: string, operation: ThreadWorkflowStateOperation, sourceTurnId?: string | null, adaptiveState?: ThreadAdaptiveWorkflowState | null, };
