// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadAdaptiveValidationStatus = { profile: string, result: string, runId: string, branch: string | null, headSha: string, failedStage: string | null, logPath: string, };
