// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadAdaptiveValidationStatus } from "./ThreadAdaptiveValidationStatus";

export type ThreadAdaptiveWorkflowState = { enabled: boolean, startingFamily: string | null, currentFamily: string | null, currentEffort: string | null, complexityClass?: string, implementationPhase?: string, validationRepairFingerprint?: string, validationRepairCyclesUsed?: number, validationTargetedRetestRequired?: boolean, validationStatus?: ThreadAdaptiveValidationStatus, attemptNumber: number, pausedByUser: boolean, workerRole: string, authorizedScope: string | null, workerAssignmentLocked: boolean, workflowTerminal: string | null, };
