// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inert data carried by the private adaptive runtime signal transport.
 *
 * These values have no policy meaning until a later trusted producer slice
 * validates and consumes them at the matching turn boundary.
 */
export type AdaptiveRuntimeSignalKind = "complexity" | "capability" | "mechanical_validation" | "implementation_work" | "ready_for_validation" | "repair_required" | "ready_for_owner_qa";
